[platformio]
default_envs = gc01-pro-ru

[env:gc01-pro-ru]
platform = ststm32@19.0.0
platform_packages =
    platformio/toolchain-gccarmnoneeabi@1.120301.0
    platformio/framework-cmsis@2.50501.200527
    platformio/framework-cmsis-stm32f1@4.3.5
    platformio/tool-ldscripts-ststm32@0.2.0
    platformio/tool-scons@4.40801.0
extra_scripts = pre:scripts/build.py
framework = cmsis
board = ch32f103r8
board_build.ldscript = scripts/gc01.ld
board_upload.offset_address = 0x08004000
board_upload.maximum_size = 45052
build_flags =
    -flto
    -fno-math-errno
    -Dlogf=__ieee754_logf
    -Dexpf=__ieee754_expf
    -Dsqrtf=__ieee754_sqrtf
    -Wl,-Map,.pio/build/gc01-pro-ru/firmware.map
    -DMCURENDERER_WITHOUT_BITMAP_SUPPORT
    -DGC01
    -DFIRMWARE_BASE=0x08004000
    -DFIRMWARE_SIZE=0xb000
    -DSTART_POWERED
    -DUSBD_ASM_DRIVER
    -DUSB_PMASIZE=0x200
    -DTUBE_HV_PWM
    -DKEYBOARD_5_KEYS
    -DKEYBOARD_KEY_POWER_OK
    -DDISPLAY_320X240
    -DDISPLAY_COLOR
    -DBUZZER
    -DVIBRATOR
    -DPULSE_LED
    -DLANGUAGE='"ru"'
    -DSTRINGS='"strings/ru.h"'
    -DFONT_SMALL='"fonts/font_small_ru_color_17_1bpp.h"'
    -DFONT_MEDIUM='"fonts/font_medium_ru_color_24_1bpp.h"'
    -DFONT_LARGE='"fonts/font_large_color_80_1bpp.h"'
    -DFONT_SYMBOLS='"fonts/font_symbols_color_1bpp.h"'
